### ISSUE TITLE
Dil ve Xorg

### ISSUE THREAD

**Issue by poyraz76** [LimeLinux/lilii#9]
/etc/mudur/locale  dile eklenmesi gerek
chroot ile Xorg :1 -configure komutu ardından
chroot ile cp /root/xorg.conf.new /etc/X11/xorg.conf komutu ile xorg ayarları ön tanımlı gelmesi gerekiyor

**Comment by mthnzbk** [comment]
220134930b318ef49b1c8bd28c1bd13fc752ebaa
